title: CLI Tools
description: "A collection of high-performance security & network tools."
baseurl: ""
url: "https://cli.gawindlin.com"

# Build settings
markdown: kramdown
permalink: pretty

# CRITICAL: Disable default theme to allow custom CSS to take over
theme: null

# Custom variables
author: gawindlin
github_username: gab-dev-7
