title: CLI Tools
description: A collection of command-line tools I've developed for various purposes.
baseurl: ""
url: "https://cli.gawindlin.com"

# Build settings
markdown: kramdown
permalink: pretty

# Custom variables
author: Gawindlin
github_username: gab-dev-7
